# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Cobalt Blue
  toc: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /images/collect_qrcode_1505745819720.jpg
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: itabas016@gmail.com
  stack-overflow:
  twitter: https://www.twitter.com/itabas16
  facebook: https://www.facebook.com/itabas16
  linkedin:
  google:
  github: https://github.com/itabas016
  weibo: http://weibo.com/struthio
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram: https://www.instagram.com/itabas016/

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: CoEy126Hk5NBPaVCgahS7P0p-gzGzoHsz
  app_key: Sd1OLyWqAE53kPjgBvFXuaCJ

# Baidu Analytics
baidu_analytics: 55dddc0bcf5586602b667550911fde04
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-50282295-4
# Google Verification
google_verification:

# Disqus
disqus_shortname: itabas016

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.6.0
